#!/usr/bin/env bash
#
# Ralph TUI Install Script
#
# Installs the Ralph TUI as a global `ralph` command.
# Supports two modes:
#   --dev   : Uses tsx to run TypeScript directly (changes picked up immediately)
#   --prod  : Builds and uses compiled JavaScript (faster startup, requires rebuild for changes)
#
# Default is --dev mode for instant source change detection.
#
set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory (where this install.sh lives)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Installation settings
INSTALL_DIR="${RALPH_INSTALL_DIR:-$HOME/.local/bin}"
COMMAND_NAME="${RALPH_COMMAND_NAME:-ralph}"
MODE="dev"  # default to dev mode

usage() {
    cat <<EOF
Ralph TUI Installer

Usage: ./install.sh [OPTIONS]

Options:
    --dev           Install in development mode (default)
                    Uses tsx to run TypeScript directly
                    Changes to source files are picked up immediately

    --prod          Install in production mode
                    Builds TypeScript to JavaScript once
                    Faster startup, but requires rebuild for changes

    --install-dir   Custom installation directory (default: ~/.local/bin)

    --name          Custom command name (default: ralph)

    --uninstall     Remove the ralph command

    -h, --help      Show this help message

Examples:
    ./install.sh                    # Install in dev mode (recommended for development)
    ./install.sh --prod             # Install in production mode
    ./install.sh --name ralph-tui   # Install as 'ralph-tui' command
    ./install.sh --uninstall        # Remove the command

Environment Variables:
    RALPH_INSTALL_DIR   Override default install directory
    RALPH_COMMAND_NAME  Override default command name
EOF
}

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_prerequisites() {
    log_info "Checking prerequisites..."

    # Check for Node.js
    if ! command -v node &> /dev/null; then
        log_error "Node.js is not installed. Please install Node.js 18+ first."
        exit 1
    fi

    NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
    if [[ "$NODE_VERSION" -lt 18 ]]; then
        log_error "Node.js 18+ is required. Found: $(node -v)"
        exit 1
    fi
    log_success "Node.js $(node -v) ✓"

    # Check for pnpm
    if ! command -v pnpm &> /dev/null; then
        log_warn "pnpm is not installed. Installing via npm..."
        npm install -g pnpm
    fi
    log_success "pnpm $(pnpm -v) ✓"
}

install_dependencies() {
    log_info "Installing dependencies..."
    cd "$SCRIPT_DIR"
    pnpm install
    log_success "Dependencies installed ✓"
}

install_tsx() {
    log_info "Ensuring tsx is available..."
    cd "$SCRIPT_DIR"

    # Check if tsx is in dev dependencies
    if ! grep -q '"tsx"' package.json; then
        log_info "Adding tsx as dev dependency..."
        pnpm add -D tsx
    fi

    log_success "tsx available ✓"
}

build_project() {
    log_info "Building TypeScript..."
    cd "$SCRIPT_DIR"
    pnpm build
    log_success "Build complete ✓"
}

create_wrapper_dev() {
    log_info "Creating development mode wrapper..."

    cat > "$INSTALL_DIR/$COMMAND_NAME" <<EOF
#!/usr/bin/env bash
#
# Ralph TUI - Development Mode Wrapper
# Source changes are picked up immediately (no rebuild needed)
#
# Generated by install.sh on $(date)
# Source directory: $SCRIPT_DIR
#

# Run tsx from the project's node_modules
exec "$SCRIPT_DIR/node_modules/.bin/tsx" "$SCRIPT_DIR/src/cli.tsx" "\$@"
EOF

    chmod +x "$INSTALL_DIR/$COMMAND_NAME"
}

create_wrapper_prod() {
    log_info "Creating production mode wrapper..."

    cat > "$INSTALL_DIR/$COMMAND_NAME" <<EOF
#!/usr/bin/env bash
#
# Ralph TUI - Production Mode Wrapper
# Uses pre-built JavaScript for faster startup
# Run './install.sh --prod' again after source changes
#
# Generated by install.sh on $(date)
# Source directory: $SCRIPT_DIR
#

exec node "$SCRIPT_DIR/dist/cli.js" "\$@"
EOF

    chmod +x "$INSTALL_DIR/$COMMAND_NAME"
}

ensure_install_dir() {
    if [[ ! -d "$INSTALL_DIR" ]]; then
        log_info "Creating install directory: $INSTALL_DIR"
        mkdir -p "$INSTALL_DIR"
    fi
}

check_path() {
    if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
        log_warn "Install directory not in PATH!"
        echo ""
        echo "Add this to your shell profile (~/.bashrc, ~/.zshrc, etc.):"
        echo ""
        echo "    export PATH=\"\$PATH:$INSTALL_DIR\""
        echo ""
        echo "Then restart your shell or run:"
        echo ""
        echo "    source ~/.bashrc  # or ~/.zshrc"
        echo ""
    fi
}

uninstall() {
    log_info "Uninstalling $COMMAND_NAME..."

    if [[ -f "$INSTALL_DIR/$COMMAND_NAME" ]]; then
        rm "$INSTALL_DIR/$COMMAND_NAME"
        log_success "Removed $INSTALL_DIR/$COMMAND_NAME ✓"
    else
        log_warn "Command not found at $INSTALL_DIR/$COMMAND_NAME"
    fi
}

main() {
    local do_uninstall=false

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            --dev)
                MODE="dev"
                shift
                ;;
            --prod)
                MODE="prod"
                shift
                ;;
            --install-dir)
                INSTALL_DIR="$2"
                shift 2
                ;;
            --name)
                COMMAND_NAME="$2"
                shift 2
                ;;
            --uninstall)
                do_uninstall=true
                shift
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                usage
                exit 1
                ;;
        esac
    done

    # Handle uninstall
    if [[ "$do_uninstall" == true ]]; then
        uninstall
        exit 0
    fi

    echo ""
    echo "╔═══════════════════════════════════════════════════════╗"
    echo "║           Ralph TUI Installer                         ║"
    echo "╚═══════════════════════════════════════════════════════╝"
    echo ""
    log_info "Mode: $MODE"
    log_info "Install directory: $INSTALL_DIR"
    log_info "Command name: $COMMAND_NAME"
    echo ""

    # Run installation steps
    check_prerequisites
    ensure_install_dir
    install_dependencies

    if [[ "$MODE" == "dev" ]]; then
        install_tsx
        create_wrapper_dev
        log_success "Installed in DEVELOPMENT mode"
        echo ""
        echo "  ✨ Source changes are picked up immediately!"
        echo "  📝 Edit files in: $SCRIPT_DIR/src/"
        echo "  🚀 Run with: $COMMAND_NAME"
        echo ""
    else
        build_project
        create_wrapper_prod
        log_success "Installed in PRODUCTION mode"
        echo ""
        echo "  ⚡ Using pre-built JavaScript for faster startup"
        echo "  🔄 After source changes, re-run: ./install.sh --prod"
        echo "  🚀 Run with: $COMMAND_NAME"
        echo ""
    fi

    check_path

    log_success "Installation complete! ✓"
    echo ""
    echo "Try it now:"
    echo ""
    echo "    $COMMAND_NAME --help"
    echo ""
}

main "$@"
